# General settings
title: CiTG Jupyter Book template
author: Colomés, Rocha, Van der Meer
logo: images/TUDelft_logo_rgb.png

# Execute notebooks when building
execute:
  execute_notebooks: auto
  exclude_patterns:
    - 'Exercises/*.ipynb'
    - 'Tutorials/*.ipynb'

sphinx:
  extra_extensions: ["sphinx_multitoc_numbering"]

html:
  use_multitoc_numbering: true
